# Generated by Django 4.1.1 on 2022-09-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_aprendizagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='dir_video',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
