# Generated by Django 4.1.1 on 2022-09-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_aprendizagem', '0002_alter_video_dir_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='dir_video',
            field=models.FilePathField(max_length=255),
        ),
    ]
