# Generated by Django 4.1.1 on 2022-10-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_aprendizagem', '0004_alter_video_dir_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='dir_video',
            field=models.URLField(max_length=255),
        ),
    ]
