# Generated by Django 4.1.1 on 2022-10-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_aprendizagem', '0005_alter_video_dir_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='dir_video',
            field=models.FileField(upload_to='video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='ds_video',
            field=models.CharField(max_length=40),
        ),
    ]
