# Generated by Django 4.1.1 on 2022-10-08 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('central_aprendizagem', '0007_faqindice_faqquestao_alter_assuntovideo_ds_assunto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssuntoVideo',
            new_name='VidAssuntoVideo',
        ),
        migrations.RenameModel(
            old_name='Video',
            new_name='VidVideo',
        ),
    ]
