# Generated by Django 4.1.1 on 2022-10-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_aprendizagem', '0008_rename_assuntovideo_vidassuntovideo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqresposta',
            name='ds_resposta',
            field=models.TextField(max_length=600),
        ),
    ]
