# Generated by Django 4.1.1 on 2022-10-08 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_aprendizagem', '0009_alter_faqresposta_ds_resposta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqindice',
            old_name='qtd_acessos',
            new_name='numero_indice',
        ),
    ]
