# Generated by Django 4.1.2 on 2022-10-21 11:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('central_aprendizagem', '0011_rename_numero_indice_faqindice_posicao_indice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqresposta',
            name='ds_resposta',
            field=tinymce.models.HTMLField(max_length=999),
        ),
    ]
