# Generated by Django 4.1.2 on 2022-11-08 13:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('central_aprendizagem', '0012_alter_faqresposta_ds_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqresposta',
            name='ds_resposta',
            field=tinymce.models.HTMLField(max_length=2000),
        ),
    ]
