# Generated by Django 4.1.1 on 2022-09-29 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_dashboard', models.URLField(max_length=255)),
                ('ds_dashboard', models.CharField(max_length=100)),
                ('dt_cadastro', models.DateTimeField(auto_now=True)),
                ('grupo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
        ),
    ]
